services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golfclub-app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/golfclub
      SPRING_DATASOURCE_USERNAME: golfuser
      SPRING_DATASOURCE_PASSWORD: golfpass
    networks:
      - golfclub-network

  mysql:
    image: mysql:8.0
    container_name: golfclub-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: golfclub
      MYSQL_USER: golfuser
      MYSQL_PASSWORD: golfpass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - golfclub-network

volumes:
  mysql_data:

networks:
  golfclub-network:
    driver: bridge